bins_pt:
- 30
- 35
- 40
- 45
- 50
- 60
- 75
- 100
- 125
- 150
- 175
- 200
- 250
- 300
- 400
- 500
- 600
- 2001

bins_eta:
- -2.5
- -2.0
- -1.5
- -1.0
- -0.5
- 0.5
- 1
- 1.5
- 2.0
- 2.51

processes:
- "TT"
- "QCD"

process-weights:
  "TT": 1.0
  "QCD": 1.0

treename:
  "DeepJetNTupler/DeepJetvars"

global_features:
- "jet_pt"
- "jet_eta"
- "nCpfcan"
- "nNpfcan"
- "nsv"
- "npv"
- "TagVarCSV_trackSumJetEtRatio"
- "TagVarCSV_trackSumJetDeltaR"
- "TagVarCSV_vertexCategory"
- "TagVarCSV_trackSip2dValAboveCharm"
- "TagVarCSV_trackSip2dSigAboveCharm"
- "TagVarCSV_trackSip3dValAboveCharm"
- "TagVarCSV_trackSip3dSigAboveCharm"
- "TagVarCSV_jetNSelectedTracks"
- "TagVarCSV_jetNTracksEtaRel"
cpf_candidates:
- "Cpfcan_BtagPf_trackEtaRel"
- "Cpfcan_BtagPf_trackPtRel"
- "Cpfcan_BtagPf_trackPPar"
- "Cpfcan_BtagPf_trackDeltaR"
- "Cpfcan_BtagPf_trackPParRatio"
- "Cpfcan_BtagPf_trackSip2dVal"
- "Cpfcan_BtagPf_trackSip2dSig"
- "Cpfcan_BtagPf_trackSip3dVal"
- "Cpfcan_BtagPf_trackSip3dSig"
- "Cpfcan_BtagPf_trackJetDistVal"
- "Cpfcan_ptrel"
- "Cpfcan_drminsv"
- "Cpfcan_VTX_ass"
- "Cpfcan_puppiw"
- "Cpfcan_chi2"
- "Cpfcan_quality"
npf_candidates:
- "Npfcan_ptrel"
- "Npfcan_deltaR"
- "Npfcan_isGamma"
- "Npfcan_HadFrac"
- "Npfcan_drminsv"
- "Npfcan_puppiw"
vtx_features:
- "sv_pt"
- "sv_deltaR"
- "sv_mass"
- "sv_ntracks"
- "sv_chi2"
- "sv_normchi2"
- "sv_dxy"
- "sv_dxysig"
- "sv_d3d"
- "sv_d3dsig"
- "sv_costhetasvpv"
- "sv_enratio"
truths:
- "isB"
- "isBB"
- "isGBB"
- "isLeptonicB"
- "isLeptonicB_C"
- "isC"
- "isCC"
- "isGCC"
- "isUD"
- "isS"
- "isG"

reference_flavour:
  "isB"

TT:
 pt_min: 30
 pt_max: 1000 

QCD:
 pt_min: 30
 pt_max: 1000
