bins_pt:
- 30
- 35
- 40
- 45
- 50
- 60
- 75
- 100
- 125
- 150
- 175
- 200
- 250
- 300
- 400
- 500
- 600
- 2001

bins_eta:
- -2.5
- -2.0
- -1.5
- -1.0
- -0.5
- 0.5
- 1
- 1.5
- 2.0
- 2.51

treename:
  "Events"

global_features:
- "nJets"
- "nbJets"
- "ncJets"
- "MET"
- "MET_phi"

jet_features:
- "sortJet_drLep1"
- "sortJet_drLep2"
- "sortJet_btagDeepFlavB"
- "sortJet_btagDeepFlavCvB"
- "sortJet_btagDeepFlavCvL"
- "sortJet_pt"
- "sortJet_eta"
- "sortJet_phi"
- "sortJet_mass"

lepton_features:
- "Lepton_pt"
- "Lepton_eta"
- "Lepton_phi"
- "Lepton_mass"

truths:
- "isttbb"
- "isttbj"
- "isttcc"
- "isttcj"
- "isttother"

reference_flavour:
  "isttcc"

